name: Build/release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # Launch yarn env && compile before launching electron-builder
          build_script_name: "prebuild"
          github_token: ${{ secrets.github_token }}
          release: true
